In [ ]:
import pandas as pd
import numpy as np

data=pd.read_csv("/content/winequality-red.csv",header=0)
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [ ]:
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
x=data.drop(columns=['quality'],axis=1)
y=data['quality']
x
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
predict=lr.predict(x_test)
print(predict)

[2 3 2 2 3 2 2 2 3 3 3 3 3 2 3 3 2 3 3 3 2 2 3 2 2 3 3 2 2 2 3 3 2 3 3 2 3
 2 3 2 2 3 2 2 3 2 2 2 3 3 3 3 3 2 2 3 3 2 2 2 3 2 3 2 3 3 3 2 2 2 2 2 3 2
 2 2 3 3 2 2 3 3 2 2 3 3 2 2 3 2 3 2 3 2 2 2 2 3 2 2 2 2 3 3 2 2 2 2 3 3 3
 3 3 2 2 2 3 3 3 2 2 2 3 2 3 2 2 2 3 2 3 3 2 2 3 3 2 2 3 3 3 3 3 3 3 3 2 3
 3 2 3 3 3 2 2 2 2 2 2 2 3 3 2 3 2 3 2 2 3 3 3 3 3 2 2 2 2 3 2 3 2 3 2 2 2
 2 3 2 2 2 2 3 2 3 3 2 3 2 3 3 2 2 3 2 3 3 3 2 2 3 2 3 2 2 3 3 3 3 3 2 3 2
 3 3 2 2 3 3 2 2 2 2 2 3 2 2 3 2 2 3 3 3 3 2 3 3 2 2 3 3 2 3 3 2 3 2 3 3 3
 2 3 3 3 3 3 2 2 2 3 3 3 3 3 3 2 2 3 3 2 2 2 3 3 3 3 2 2 2 3 2 2 2 3 3 2 3
 3 3 3 2 2 2 2 2 3 2 3 3 2 2 2 3 3 3 3 3 2 2 2 3]

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,predict)
print("testing accurscy:",acc)

testing accurscy: 0.56875

In [ ]:
test_values=[]
N=float(input("fixed acidity:"))
test_values.append(N)
P=float(input("volatile acidity:"))
test_values.append(P)
K=float(input("citric acid:"))
test_values.append(K)
F=float(input("residual sugar:"))
test_values.append(F)
I=float(input("chlorides:"))
test_values.append(I)
B=float(input("free sulfur dioxide:"))
test_values.append(B)
D=float(input("total sulfur dioxide:"))
test_values.append(D)
A=float(input("density:"))
test_values.append(A)
S=float(input("pH:"))
test_values.append(S)
T=float(input("sulphates:"))
test_values.append(T)
O=float(input("alcohol:"))
test_values.append(O)
print("This is your test report",test_values)
#Convert test_values directly to a NumPy array2222
data=np.asarray(test_values)
data=data.reshape(1,-1)
predict=lr.predict(data)
print("Quality:",predict)

fixed acidity:10
volatile acidity:.2
citric acid:1
residual sugar:4
chlorides:5
free sulfur dioxide:12
total sulfur dioxide:.03
density:2
pH:5
sulphates:4
alcohol:12.
This is your test report [10.0, 0.2, 1.0, 4.0, 5.0, 12.0, 0.03, 2.0, 5.0, 4.0, 12.0]
Quality: [3]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(